# 🔍 Week 6: Named Entity Recognition (NER)

## Tujuan Pembelajaran:
1. Memahami konsep **Named Entity Recognition (NER)** — mengidentifikasi dan mengklasifikasikan entitas bernama (nama orang, lokasi, organisasi, dll.) dalam teks
2. Menggunakan model **spaCy pretrained** (`en_core_web_sm`) untuk NER pada teks Inggris
3. Mengenal jenis-jenis entitas dalam skema **OntoNotes** yang digunakan spaCy
4. Menerapkan **EntityRuler** untuk menambahkan aturan NER berbasis pola (phrase & token matching)
5. Melakukan NER pada **teks bahasa Indonesia** menggunakan model **BERT** (`cahya/bert-base-indonesian-NER`)
6. Menerapkan NER ke seluruh dataset ulasan Honest Review

---
> 📂 **Dataset**: Honest Review (`cleandata.csv`) — kolom `text_final` (teks yang sudah dipreproses)
> File ini berada di folder `Week 3/` dalam workspace yang sama.

## 1) Install Library

Install spaCy, model bahasa Inggris, dan library Transformers untuk model NER bahasa Indonesia.

In [1]:
%pip install spacy transformers sentencepiece pandas openpyxl

Collecting spacy
  Downloading spacy-3.8.13-cp314-cp314-win_amd64.whl.metadata (28 kB)
Requirement already satisfied: transformers in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (5.5.0)
Collecting sentencepiece
  Downloading sentencepiece-0.2.1-cp314-cp314-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: openpyxl in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (3.1.5)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp314-cp314-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp314-cp314-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp314-cp314-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp314-cp314-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Downloading confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from spacy) (2.4.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from spacy) (2.33.1)
Collecting pydantic<3.0.0,>=2.0.0 (from spacy)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: jinja2 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from spacy) (81.0.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from spacy) (26.0)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3.0.0,>=2.0.0->spacy)
  Downloading pydantic_core-2.41.5-cp314-cp314-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp314-cp314-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: colorama in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached smart_open-7.5.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: httpx>=0.24.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from transformers) (1.9.1)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: anyio in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: et-xmlfile in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting wrapt (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy)
  Downloading wrapt-2.1.2-cp314-cp314-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages (from jinja2->spacy) (3.0.3)
Downloading spacy-3.8.13-cp314-cp314-win_amd64.whl (14.4 MB)
   ---------------------------------------- 0.0/14.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.4 MB ? eta -:--:--
    --------------------------------------- 0.3/14.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.4 MB 798.3 kB/s eta 0:00:18
   - -------------------------------------- 0.5/14.4 MB 798.3 kB/s eta 0:00:18
   -- ------------------------------------- 0.8/14.4 MB 726.7 kB/s eta 0:00:19
   -- ------------------------------------- 0.8/14.4 MB 726.7 kB/s eta 0:00:19
   -- ------------------------------------- 1.0/14.4 MB 761.4 kB/s eta 0:00:18
   --- ------------------------------------ 1.3/14.4 MB 745.7 kB/s eta 0:00:18
   --- ------------------------------------ 1.3/14.4 MB 745.7 kB/s eta 0:00:18
   --- ------------------------------------ 1.3/14.4 MB 745.7 kB/s eta 0:00:18
   ----- ---------------------------------- 1.8/14.4 MB 761.2 kB/s eta 0:00:17
   ----- ---------------------------------- 1.8/14.4 MB 761.2 kB/s eta 0:00:17
   ----- ---------------------------------- 2.1/14.4 MB 777.4 kB/s eta 0:00:16
   ------ --------------------------------- 2.4/14.4 MB 816.5 kB/s eta 0:00:15
   ------- -------------------------------- 2.6/14.4 MB 838.4 kB/s eta 0:00:15
   ------- -------------------------------- 2.6/14.4 MB 838.4 kB/s eta 0:00:15
   -------- ------------------------------- 2.9/14.4 MB 797.3 kB/s eta 0:00:15
   -------- ------------------------------- 2.9/14.4 MB 797.3 kB/s eta 0:00:15
   -------- ------------------------------- 2.9/14.4 MB 797.3 kB/s eta 0:00:15
   -------- ------------------------------- 3.1/14.4 MB 762.1 kB/s eta 0:00:15
   -------- ------------------------------- 3.1/14.4 MB 762.1 kB/s eta 0:00:15
   -------- ------------------------------- 3.1/14.4 MB 762.1 kB/s eta 0:00:15
   --------- ------------------------------ 3.4/14.4 MB 688.3 kB/s eta 0:00:16
   --------- ------------------------------ 3.4/14.4 MB 688.3 kB/s eta 0:00:16
   ---------- ----------------------------- 3.7/14.4 MB 681.5 kB/s eta 0:00:16
   ---------- ----------------------------- 3.7/14.4 MB 681.5 kB/s eta 0:00:16
   ---------- ----------------------------- 3.7/14.4 MB 681.5 kB/s eta 0:00:16
   ---------- ----------------------------- 3.7/14.4 MB 681.5 kB/s eta 0:00:16
   ---------- ----------------------------- 3.9/14.4 MB 637.4 kB/s eta 0:00:17
   ---------- ----------------------------- 3.9/14.4 MB 637.4 kB/s eta 0:00:17
   ---------- ----------------------------- 3.9/14.4 MB 637.4 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.4 MB 611.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.4 MB 611.8 kB/s eta 0:00:17
   ------------ --------------------------- 4.5/14.4 MB 605.1 kB/s eta 0:00:17
   ------------ --------------------------- 4.5/14.4 MB 605.1 kB/s eta 0:00:17
   ------------- -------------------------- 4.7/14.4 MB 612.5 kB/s eta 0:00:16
   ------------- -------------------------- 4.7/14.4 MB 612.5 kB/s eta 0:00:16
   ------------- -------------------------- 5.0/14.4 MB 614.5 kB/s eta 0:00:16
   ------------- -------------------------- 5.0/14.4 MB 614.5 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   -------------- ------------------------- 5.2/14.4 MB 610.4 kB/s eta 0:00:16
   --------------- ------------------------ 5.5/14.4 MB 502.7 kB/s eta 0:00:18
   ---------------- ----------------------- 5.8/14.4 MB 514.5 kB/s eta 0:00:17
   ---------------- ----------------------- 5.8/14.4 MB 514.5 kB/s eta 0:00:17
   ---------------- ----------------------- 5.8/14.4 MB 514.5 kB/s eta 0:00:17
   ---------------- ----------------------- 6.0/14.4 MB 511.8 kB/s eta 0:00:17
   ----------------- ---------------------- 6.3/14.4 MB 521.1 kB/s eta 0:00:16
   ------------------ --------------------- 6.6/14.4 MB 537.0 kB/s eta 0:00:15
   ------------------ --------------------- 6.8/14.4 MB 554.5 kB/s eta 0:00:14
   ------------------- -------------------- 7.1/14.4 MB 566.7 kB/s eta 0:00:13
   -------------------- ------------------- 7.3/14.4 MB 578.4 kB/s eta 0:00:13
   --------------------- ------------------ 7.6/14.4 MB 588.7 kB/s eta 0:00:12
   --------------------- ------------------ 7.6/14.4 MB 588.7 kB/s eta 0:00:12
   --------------------- ------------------ 7.9/14.4 MB 589.2 kB/s eta 0:00:12
   --------------------- ------------------ 7.9/14.4 MB 589.2 kB/s eta 0:00:12
   ---------------------- ----------------- 8.1/14.4 MB 586.3 kB/s eta 0:00:11
   ---------------------- ----------------- 8.1/14.4 MB 586.3 kB/s eta 0:00:11
   ----------------------- ---------------- 8.4/14.4 MB 587.9 kB/s eta 0:00:11
   ----------------------- ---------------- 8.4/14.4 MB 587.9 kB/s eta 0:00:11
   ------------------------ --------------- 8.7/14.4 MB 587.2 kB/s eta 0:00:10
   ------------------------ --------------- 8.7/14.4 MB 587.2 kB/s eta 0:00:10
   ------------------------ --------------- 8.7/14.4 MB 587.2 kB/s eta 0:00:10
   ------------------------ --------------- 8.7/14.4 MB 587.2 kB/s eta 0:00:10
   ------------------------ --------------- 8.9/14.4 MB 578.9 kB/s eta 0:00:10
   ------------------------ --------------- 8.9/14.4 MB 578.9 kB/s eta 0:00:10
   ------------------------- -------------- 9.2/14.4 MB 575.6 kB/s eta 0:00:10
   ------------------------- -------------- 9.2/14.4 MB 575.6 kB/s eta 0:00:10
   -------------------------- ------------- 9.4/14.4 MB 576.9 kB/s eta 0:00:09
   -------------------------- ------------- 9.4/14.4 MB 576.9 kB/s eta 0:00:09
   -------------------------- ------------- 9.4/14.4 MB 576.9 kB/s eta 0:00:09
   -------------------------- ------------- 9.7/14.4 MB 576.0 kB/s eta 0:00:09
   -------------------------- ------------- 9.7/14.4 MB 576.0 kB/s eta 0:00:09
   -------------------------- ------------- 9.7/14.4 MB 576.0 kB/s eta 0:00:09
   --------------------------- ------------ 10.0/14.4 MB 570.3 kB/s eta 0:00:08
   --------------------------- ------------ 10.0/14.4 MB 570.3 kB/s eta 0:00:08
   ---------------------------- ----------- 10.2/14.4 MB 571.3 kB/s eta 0:00:08
   ----------------------------- ---------- 10.5/14.4 MB 573.2 kB/s eta 0:00:07
   ----------------------------- ---------- 10.5/14.4 MB 573.2 kB/s eta 0:00:07
   ------------------------------ --------- 11.0/14.4 MB 589.6 kB/s eta 0:00:06
   ------------------------------- -------- 11.3/14.4 MB 595.7 kB/s eta 0:00:06
   ------------------------------- -------- 11.3/14.4 MB 595.7 kB/s eta 0:00:06
   -------------------------------- ------- 11.5/14.4 MB 601.2 kB/s eta 0:00:05
   -------------------------------- ------- 11.5/14.4 MB 601.2 kB/s eta 0:00:05
   -------------------------------- ------- 11.8/14.4 MB 602.2 kB/s eta 0:00:05
   --------------------------------- ------ 12.1/14.4 MB 607.1 kB/s eta 0:00:04
   ---------------------------------- ----- 12.3/14.4 MB 613.5 kB/s eta 0:00:04
   ---------------------------------- ----- 12.3/14.4 MB 613.5 kB/s eta 0:00:04
   ---------------------------------- ----- 12.6/14.4 MB 617.6 kB/s eta 0:00:03
   ---------------------------------- ----- 12.6/14.4 MB 617.6 kB/s eta 0:00:03
   ----------------------------------- ---- 12.8/14.4 MB 617.7 kB/s eta 0:00:03
   ------------------------------------ --- 13.1/14.4 MB 621.6 kB/s eta 0:00:03
   ------------------------------------- -- 13.4/14.4 MB 624.7 kB/s eta 0:00:02
   ------------------------------------- -- 13.4/14.4 MB 624.7 kB/s eta 0:00:02
   ------------------------------------- -- 13.6/14.4 MB 628.3 kB/s eta 0:00:02
   -------------------------------------- - 13.9/14.4 MB 630.6 kB/s eta 0:00:01
   -------------------------------------- - 13.9/14.4 MB 630.6 kB/s eta 0:00:01
   ---------------------------------------  14.2/14.4 MB 634.2 kB/s eta 0:00:01
   ---------------------------------------- 14.4/14.4 MB 637.5 kB/s  0:00:22
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp314-cp314-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp314-cp314-win_amd64.whl (26 kB)
Downloading preshed-3.0.13-cp314-cp314-win_amd64.whl (125 kB)
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Downloading pydantic_core-2.41.5-cp314-cp314-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 785.3 kB/s eta 0:00:02
   ---------- ----------------------------- 0.5/2.0 MB 785.3 kB/s eta 0:00:02
   --------------- ------------------------ 0.8/2.0 MB 723.3 kB/s eta 0:00:02
   -------------------- ------------------- 1.0/2.0 MB 718.4 kB/s eta 0:00:02
   -------------------- ------------------- 1.0/2.0 MB 718.4 kB/s eta 0:00:02
   -------------------- ------------------- 1.0/2.0 MB 718.4 kB/s eta 0:00:02
   -------------------------- ------------- 1.3/2.0 MB 656.6 kB/s eta 0:00:02
   -------------------------- ------------- 1.3/2.0 MB 656.6 kB/s eta 0:00:02
   ------------------------------- -------- 1.6/2.0 MB 656.2 kB/s eta 0:00:01
   ------------------------------- -------- 1.6/2.0 MB 656.2 kB/s eta 0:00:01
   ------------------------------- -------- 1.6/2.0 MB 656.2 kB/s eta 0:00:01
   ------------------------------- -------- 1.6/2.0 MB 656.2 kB/s eta 0:00:01
   ------------------------------- -------- 1.6/2.0 MB 656.2 kB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 571.3 kB/s  0:00:03
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp314-cp314-win_amd64.whl (656 kB)
   ---------------------------------------- 0.0/656.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/656.5 kB ? eta -:--:--
   --------------- ------------------------ 262.1/656.5 kB ? eta -:--:--
   ------------------------------ ------- 524.3/656.5 kB 888.2 kB/s eta 0:00:01
   ------------------------------ ------- 524.3/656.5 kB 888.2 kB/s eta 0:00:01
   ---------------------------------------- 656.5/656.5 kB 643.2 kB/s  0:00:00
Downloading thinc-8.3.13-cp314-cp314-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--

In [3]:
# Download model spaCy bahasa Inggris
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - ------------------------------------- 0.5/12.8 MB 304.5 kB/s eta 0:00:41
     - ------------------------------------- 0.5/12.8 MB 304.5 kB/s eta 0:00:41
     - ------------------------------------- 0.5/12.8 MB 304.5 kB/s eta 0:00:41
     -- ------------------------------------ 0.8/12.8 MB 392.4 kB/s eta 0:00:31
     -- ------------------------------------ 0.8/12.8 MB 392.4 kB/s eta 0:00:31
     --- ----------------------------------- 1.0/12.8 MB 418.3 kB/s eta 0:00:29
     --- ----------------------------------- 1.0/12.8 MB 418.3 kB/s eta 0:00:29
     --- ----------------------------------- 1.0/12.8 MB 418.3 kB/s eta 0:00:29
     --- ----------------------------------- 1.0/12.8 MB 418.3 kB/s eta 0:00:29
     --- ----------------------------------- 1.0/12.8 MB 418.3 kB/s eta 0:00:29
     --- ----------------------------------- 1.3/12.8 MB 371.4 kB/s eta 0:00:31
     --- ----------------------------------- 1.3/12.8 MB 371.4 kB/s eta 0:00:31
     ---- ---------------------------------- 1.6/12.8 MB 396.2 kB/s eta 0:00:29
     ---- ---------------------------------- 1.6/12.8 MB 396.2 kB/s eta 0:00:29
     ----- --------------------------------- 1.8/12.8 MB 414.6 kB/s eta 0:00:27
     ----- --------------------------------- 1.8/12.8 MB 414.6 kB/s eta 0:00:27
     ----- --------------------------------- 1.8/12.8 MB 414.6 kB/s eta 0:00:27
     ------ -------------------------------- 2.1/12.8 MB 419.2 kB/s eta 0:00:26
     ------ -------------------------------- 2.1/12.8 MB 419.2 kB/s eta 0:00:26
     ------- ------------------------------- 2.4/12.8 MB 430.0 kB/s eta 0:00:25
     ------- ------------------------------- 2.4/12.8 MB 430.0 kB/s eta 0:00:25
     ------- ------------------------------- 2.4/12.8 MB 430.0 kB/s eta 0:00:25
     ------- ------------------------------- 2.6/12.8 MB 428.9 kB/s eta 0:00:24
     ------- ------------------------------- 2.6/12.8 MB 428.9 kB/s eta 0:00:24
     ------- ------------------------------- 2.6/12.8 MB 428.9 kB/s eta 0:00:24
     -------- ------------------------------ 2.9/12.8 MB 432.9 kB/s eta 0:00:23
     -------- ------------------------------ 2.9/12.8 MB 432.9 kB/s eta 0:00:23
     --------- ----------------------------- 3.1/12.8 MB 444.9 kB/s eta 0:00:22
     --------- ----------------------------- 3.1/12.8 MB 444.9 kB/s eta 0:00:22
     --------- ----------------------------- 3.1/12.8 MB 444.9 kB/s eta 0:00:22
     ---------- ---------------------------- 3.4/12.8 MB 445.7 kB/s eta 0:00:22
     ---------- ---------------------------- 3.4/12.8 MB 445.7 kB/s eta 0:00:22
     ---------- ---------------------------- 3.4/12.8 MB 445.7 kB/s eta 0:00:22
     ----------- --------------------------- 3.7/12.8 MB 446.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.7/12.8 MB 446.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.7/12.8 MB 446.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.9/12.8 MB 444.0 kB/s eta 0:00:20
     ----------- --------------------------- 3.9/12.8 MB 444.0 kB/s eta 0:00:20
     ----------- --------------------------- 3.9/12.8 MB 444.0 kB/s eta 0:00:20
     ------------ -------------------------- 4.2/12.8 MB 440.7 kB/s eta 0:00:20
     ------------ -------------------------- 4.2/12.8 MB 440.7 kB/s eta 0:00:20
     ------------- ------------------------- 4.5/12.8 MB 447.4 kB/s eta 0:00:19
     -------------- ------------------------ 4.7/12.8 MB 464.9 kB/s eta 0:00:18
     -------------- ------------------------ 4.7/12.8 MB 464.9 kB/s eta 0:00:18
     -------------- ------------------------ 4.7/12.8 MB 464.9 kB/s eta 0:00:18
     --------------- ----------------------- 5.0/12.8 MB 460.9 kB/s eta 0:00:17
     --------------- ----------------------- 5.0/12.8 MB 460.9 kB/s eta 0:00:17
     --------------- ----------------------- 5.0/12.8 MB 460.9 kB/s eta 0:00:17
     --------------- ----------------------- 5.2/12.8 MB 456.6 kB/s eta 0:00:17
     --------------- ----------------------- 5.2/12.8 MB 456.6 kB/s eta 0:00:17
     ---------------- ---------------------- 5.5/12.8 MB 463.9 kB/s eta 0:00:16
     ---------------- ---------------------- 5.5/12.8 MB 463.9 kB/s eta 0:00:16
     ---------------- ---------------------- 5.5/12.8 MB 463.9 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ----------------- --------------------- 5.8/12.8 MB 461.8 kB/s eta 0:00:16
     ------------------ -------------------- 6.0/12.8 MB 415.3 kB/s eta 0:00:17
     ------------------ -------------------- 6.0/12.8 MB 415.3 kB/s eta 0:00:17
     ------------------ -------------------- 6.0/12.8 MB 415.3 kB/s eta 0:00:17
     ------------------ -------------------- 6.0/12.8 MB 415.3 kB/s eta 0:00:17
     ------------------ -------------------- 6.0/12.8 MB 415.3 kB/s eta 0:00:17
     ------------------ -------------------- 6.0/12.8 MB 415.3 kB/s eta 0:00:17
     ------------------- ------------------- 6.3/12.8 MB 395.8 kB/s eta 0:00:17
     ------------------- ------------------- 6.3/12.8 MB 395.8 kB/s eta 0:00:17
     ------------------- ------------------- 6.6/12.8 MB 406.1 kB/s eta 0:00:16
     ------------------- ------------------- 6.6/12.8 MB 406.1 kB/s eta 0:00:16
     -------------------- ------------------ 6.8/12.8 MB 409.0 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 409.0 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 409.0 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 409.0 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 409.0 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 409.0 kB/s eta 0:00:15
     --------------------- ----------------- 7.1/12.8 MB 395.1 kB/s eta 0:00:15
     --------------------- ----------------- 7.1/12.8 MB 395.1 kB/s eta 0:00:15
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ---------------------- ---------------- 7.3/12.8 MB 399.9 kB/s eta 0:00:14
     ----------------------- --------------- 7.6/12.8 MB 381.7 kB/s eta 0:00:14
     ----------------------- --------------- 7.6/12.8 MB 381.7 kB/s eta 0:00:14
     ----------------------- --------------- 7.9/12.8 MB 387.1 kB/s eta 0:00:13
     ------------------------ -------------- 8.1/12.8 MB 395.1 kB/s eta 0:00:12
     ------------------------ -------------- 8.1/12.8 MB 395.1 kB/s eta 0:00:12
     ------------------------- ------------- 8.4/12.8 MB 400.6 kB/s eta 0:00:12
     -------------------------- ------------ 8.7/12.8 MB 406.6 kB/s eta 0:00:11
     -------------------------- ------------ 8.7/12.8 MB 406.6 kB/s eta 0:00:11
     --------------------------- ----------- 8.9/12.8 MB 412.0 kB/s eta 0:00:10
     --------------------------- ----------- 8.9/12.8 MB 412.0 kB/s eta 0:00:10
     --------------------------- ----------- 9.2/12.8 MB 416.9 kB/s eta 0:00:09
     --------------------------- ----------- 9.2/12.8 MB 416.9 kB/s eta 0:00:09
     --------------------------- ----------- 9.2/12.8 MB 416.9 kB/s eta 0:00:09
     --------------------------- ----------- 9.2/12.8 MB 416.9 kB/s eta 0:00:09
     ---------------------------- ---------- 9.4/12.8 MB 412.7 kB/s eta 0:00:09
     ---------------------------- ---------- 9.4/12.8 MB 412.7 kB/s eta 0:00:09
     ---------------------------- ---------- 9.4/12.8 MB 412.7 kB/s eta 0:00:09
     ---------------------------- ---------- 9.4/12.8 MB 412.7 kB/s eta 0:00:09
     ---------------------------- ---------- 9.4/12.8 MB 412.7 kB/s eta 0:00:09
     ---------------------------- ---------- 9.4/12.8 MB 412.7 kB/s eta 0:00:09
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 403.2 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 363.0 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 346.3 kB/s eta 0:00:08
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 334.7 kB/s eta 0:00:07
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     ------------------------------- ------ 10.7/12.8 MB 194.6 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     -------------------------------- ----- 11.0/12.8 MB 175.4 kB/s eta 0:00:11
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     --------------------------------- ---- 11.3/12.8 MB 172.2 kB/s eta 0:00:09
     ---------------------------------- --- 11.5/12.8 MB 157.9 kB/s eta 0:00:09
     ---------------------------------- --- 11.5/12.8 MB 157.9 kB/s eta 0:00:09
     ---------------------------------- --- 11.5/12.8 MB 157.9 kB/s eta 0:00:09
     ---------------------------------- --- 11.5/12.8 MB 157.9 kB/s eta 0:00:09
     ---------------------------------- --- 11.5/12.8 MB 157.9 kB/s eta 0:00:09
     ---------------------------------- --- 11.5/12.8 MB 157.9 kB/s eta 0:00:09
     ---------------------------------- --- 11.5/12.8 MB 157.9 kB/s eta 0:00:09
     ----------------------------------- -- 11.8/12.8 MB 150.3 kB/s eta 0:00:07
     ----------------------------------- -- 11.8/12.8 MB 150.3 kB/s eta 0:00:07
     ----------------------------------- -- 11.8/12.8 MB 150.3 kB/s eta 0:00:07
     ----------------------------------- -- 11.8/12.8 MB 150.3 kB/s eta 0:00:07
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ----------------------------------- -- 12.1/12.8 MB 153.4 kB/s eta 0:00:05
     ------------------------------------ - 12.3/12.8 MB 123.2 kB/s eta 0:00:04
     -------------------------------------  12.6/12.8 MB 123.3 kB/s eta 0:00:02
     -------------------------------------  12.6/12.8 MB 123.3 kB/s eta 0:00:02
     -------------------------------------  12.6/12.8 MB 123.3 kB/s eta 0:00:02

## 2) NER dengan spaCy — Model Pretrained

spaCy menyediakan model NER yang sudah dilatih pada corpus besar. Model `en_core_web_sm` dapat mengenali entitas seperti nama orang, organisasi, lokasi, tanggal, dan lainnya dari teks Inggris.

Pipeline spaCy terdiri dari:
1. `tok2vec` — representasi token
2. `tagger` — POS tagging
3. `parser` — dependency parsing
4. `ner` — named entity recognition

In [4]:
import spacy
from spacy import displacy

# Load model spaCy bahasa Inggris
nlp = spacy.load('en_core_web_sm')
print("Model spaCy berhasil dimuat.")
print(f"Pipeline: {nlp.pipe_names}")

Model spaCy berhasil dimuat.
Pipeline: ['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [5]:
# Contoh NER pada teks Inggris
text = (
    "George Washington was the first president of the United States. "
    "He was born on February 22, 1732, in Virginia. "
    "He led the Continental Army and later served two terms as president."
)

doc = nlp(text)

print("Entitas yang ditemukan:")
print(f"{'Entitas':<30} {'Label':<12} {'Keterangan'}")
print('-' * 65)
for ent in doc.ents:
    print(f"{ent.text:<30} {ent.label_:<12} {spacy.explain(ent.label_)}")

Entitas yang ditemukan:
Entitas                        Label        Keterangan
-----------------------------------------------------------------
George Washington              PERSON       People, including fictional
first                          ORDINAL      "first", "second", etc.
the United States              GPE          Countries, cities, states
February 22, 1732              DATE         Absolute or relative dates or periods
Virginia                       GPE          Countries, cities, states
the Continental Army           ORG          Companies, agencies, institutions, etc.
two                            CARDINAL     Numerals that do not fall under another type

In [6]:
# Visualisasi NER dengan displacy
displacy.render(doc, style='ent', jupyter=True)

## 3) Jenis Entitas OntoNotes (spaCy)

spaCy menggunakan skema entity **OntoNotes 5**. Berikut daftar lengkap entitas yang didukung:

| Label      | Keterangan |
|------------|------------|
| `PERSON`   | Nama orang, termasuk tokoh fiksi |
| `NORP`     | Kebangsaan, kelompok agama atau politik |
| `FAC`      | Fasilitas: bangunan, bandara, jembatan, jalan |
| `ORG`      | Perusahaan, lembaga, instansi pemerintah |
| `GPE`      | Negara, kota, provinsi |
| `LOC`      | Lokasi non-GPE: gunung, lautan, sungai |
| `PRODUCT`  | Objek, kendaraan, makanan |
| `EVENT`    | Perang, pertempuran, olahraga, dll. |
| `WORK_OF_ART` | Judul buku, lagu, karya seni |
| `LAW`      | Peraturan, undang-undang |
| `LANGUAGE` | Bahasa yang disebutkan |
| `DATE`     | Tanggal atau periode waktu |
| `TIME`     | Waktu lebih kecil dari sehari |
| `PERCENT`  | Persentase |
| `MONEY`    | Nilai moneter |
| `QUANTITY` | Ukuran, berat, jarak |
| `ORDINAL`  | "pertama", "kedua", dll. |
| `CARDINAL` | Angka yang tidak termasuk kategori lain |

In [7]:
# Cetak semua entitas yang didukung model
print("Entitas yang dikenali oleh model en_core_web_sm:")
for label in nlp.get_pipe('ner').labels:
    print(f"  {label:<15} → {spacy.explain(label)}")

Entitas yang dikenali oleh model en_core_web_sm:
  CARDINAL        → Numerals that do not fall under another type
  DATE            → Absolute or relative dates or periods
  EVENT           → Named hurricanes, battles, wars, sports events, etc.
  FAC             → Buildings, airports, highways, bridges, etc.
  GPE             → Countries, cities, states
  LANGUAGE        → Any named language
  LAW             → Named documents made into laws.
  LOC             → Non-GPE locations, mountain ranges, bodies of water
  MONEY           → Monetary values, including unit
  NORP            → Nationalities or religious or political groups
  ORDINAL         → "first", "second", etc.
  ORG             → Companies, agencies, institutions, etc.
  PERCENT         → Percentage, including "%"
  PERSON          → People, including fictional
  PRODUCT         → Objects, vehicles, foods, etc. (not services)
  QUANTITY        → Measurements, as of weight or distance
  TIME            → Times smaller than a day
  WORK_OF_ART     → Titles of books, songs, etc.

## 4) EntityRuler — Phrase Matching (Aturan Berbasis Teks Eksak)

**EntityRuler** memungkinkan kita mendefinisikan aturan NER berbasis pola, bukan statistik. Berguna ketika:
- Ada daftar nama yang pasti (misalnya: nama presiden, nama kota)
- Entitas memiliki pola yang sangat terstruktur (misalnya: nomor IP, kode produk)

**Phrase patterns** cocok untuk pencocokan string eksak.

In [8]:
# Tambahkan EntityRuler ke pipeline — SEBELUM komponen 'ner'
# Ini penting agar 'ner' menghormati label dari EntityRuler
ruler = nlp.add_pipe("entity_ruler", before="ner", name="presidents")

# Daftar nama presiden AS
presidents = [
    "George Washington", "John Adams", "Thomas Jefferson", "Abraham Lincoln",
    "Franklin D. Roosevelt", "Harry S. Truman", "Dwight D. Eisenhower",
    "John F. Kennedy", "Lyndon B. Johnson", "Richard Nixon",
    "Jimmy Carter", "Ronald Reagan", "George H.W. Bush",
    "Bill Clinton", "George W. Bush", "Barack Obama", "Donald Trump"
]

def make_patterns(name_list, label):
    """Ubah list nama menjadi format pola EntityRuler."""
    return [{"label": label, "pattern": name} for name in name_list]

# Tambahkan pola ke EntityRuler
ruler.add_patterns(make_patterns(presidents, "PRES"))

print(f"EntityRuler ditambahkan. Pipeline: {nlp.pipe_names}")
print(f"Jumlah pola terdaftar: {len(ruler.patterns)}")

EntityRuler ditambahkan. Pipeline: ['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'presidents', 'ner']
Jumlah pola terdaftar: 17

In [9]:
# Test EntityRuler
text2 = (
    "Barack Obama and George W. Bush both attended the inauguration of Donald Trump "
    "at the Capitol in Washington D.C. in January 2017."
)

doc2 = nlp(text2)

print("Entitas yang ditemukan (dengan EntityRuler):")
print(f"{'Entitas':<30} {'Label'}")
print('-' * 45)
for ent in doc2.ents:
    print(f"{ent.text:<30} {ent.label_}")

print()
displacy.render(doc2, style='ent', jupyter=True)

Entitas yang ditemukan (dengan EntityRuler):
Entitas                        Label
---------------------------------------------
Barack Obama                   PRES
George W. Bush                 PRES
Donald Trump                   PRES
Capitol                        FAC
Washington D.C.                GPE
January 2017                   DATE

## 5) EntityRuler — Token Patterns (Aturan Berbasis Atribut Token)

**Token patterns** lebih fleksibel dari phrase patterns — bisa menggunakan regex dan atribut seperti `LOWER`, `POS`, `SHAPE`.

Contoh: mencocokkan berbagai cara penulisan nama "George H.W. Bush":
- 2 token: `george bush`
- 3 token: `george hw bush`, `george h.w. bush`
- 4 token: `george h. w. bush`, `george herbert walker bush`

In [10]:
# Hapus EntityRuler lama dan buat ulang dengan token patterns
nlp.remove_pipe('presidents')
ruler2 = nlp.add_pipe("entity_ruler", before="ner", name="presidents")

token_patterns = [
    # 2 token: "george bush"
    {"id": "PRES41", "label": "PRES",
     "pattern": [{"LOWER": "george"}, {"LOWER": "bush"}]},

    # 3 token: "george hw bush", "george h.w. bush"
    {"id": "PRES41", "label": "PRES",
     "pattern": [{"LOWER": "george"}, {"LOWER": {"REGEX": "h(\\.w\\.?|w)"}}, {"LOWER": "bush"}]},

    # 4 token: "george herbert walker bush"
    {"id": "PRES41", "label": "PRES",
     "pattern": [{"LOWER": "george"}, {"LOWER": {"REGEX": "h(erbert|\\.?)"}},
                 {"LOWER": {"REGEX": "w(alker|\\.?)"}}, {"LOWER": "bush"}]},
]

ruler2.add_patterns(token_patterns)

# Uji berbagai format nama
text3 = (
    "Known names: George Bush, George HW Bush, George H.W. Bush, "
    "George Herbert Walker Bush. His son George W. Bush was also president."
)
doc3 = nlp(text3)

print("Entitas yang ditemukan (Token Patterns):")
for ent in doc3.ents:
    print(f"  {ent.text!r:<40} → {ent.label_}")

displacy.render(doc3, style='ent', jupyter=True)

Entitas yang ditemukan (Token Patterns):
  'George Bush'                            → PRES
  'George HW Bush'                         → PRES
  'George H.W. Bush'                       → PRES
  'George Herbert Walker Bush'             → PRES
  'George W. Bush'                         → PERSON

## 6) NER Bahasa Indonesia dengan BERT

Untuk teks bahasa Indonesia, kita menggunakan model **`cahya/bert-base-indonesian-NER`** — model BERT yang dilatih khusus untuk NER pada teks Indonesia. Model ini mengenali entitas:

| Label | Keterangan |
|-------|------------|
| `PER` | Nama orang (Person) |
| `ORG` | Organisasi |
| `LOC` | Lokasi |
| `QTY` | Kuantitas |
| `EVT` | Event/Kejadian |
| `PRD` | Produk |
| `TIM` | Waktu |

In [11]:
from transformers import pipeline, AutoTokenizer

# Load tokenizer dan model NER bahasa Indonesia
print("Loading model NER bahasa Indonesia (cahya/bert-base-indonesian-NER)...")
tokenizer = AutoTokenizer.from_pretrained("cahya/bert-base-indonesian-NER")
ner_pipeline_id = pipeline(
    "ner",
    model="cahya/bert-base-indonesian-NER",
    tokenizer=tokenizer,
    aggregation_strategy="simple"  # Gabungkan sub-token menjadi satu entitas
)
print("Model berhasil dimuat!")

c:\Users\mikba\Downloads\Documents\PBA\PBA\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading model NER bahasa Indonesia (cahya/bert-base-indonesian-NER)...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 30135.63it/s]
BertForTokenClassification LOAD REPORT from: cahya/bert-base-indonesian-NER
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.pooler.dense.bias       | UNEXPECTED |  |
bert.pooler.dense.weight     | UNEXPECTED |  |
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Model berhasil dimuat!

In [12]:
# Uji NER pada kalimat bahasa Indonesia
teks_id = "Jokowi mengunjungi Bandung untuk meresmikan proyek infrastruktur baru bersama Menteri PUPR Basuki."

results = ner_pipeline_id(teks_id)

print("=== Hasil NER Bahasa Indonesia ===")
print(f"Teks: {teks_id}\n")
print(f"{'Token':<25} {'Entitas':<10} {'Score'}")
print('-' * 50)
for r in results:
    print(f"{r['word']:<25} {r['entity_group']:<10} {r['score']:.4f}")

=== Hasil NER Bahasa Indonesia ===
Teks: Jokowi mengunjungi Bandung untuk meresmikan proyek infrastruktur baru bersama Menteri PUPR Basuki.

Token                     Entitas    Score
--------------------------------------------------
jokowi                    PER        0.9877
bandung                   GPE        0.9920
menteri pupr              NOR        0.9467
basuki                    PER        0.9905

In [ ]:
# Contoh lain: teks berkaitan dengan ulasan produk keuangan Indonesia
teks_id2 = (
    "BCA dan Mandiri bekerja sama dengan OJK untuk meningkatkan "
    "layanan perbankan digital di Jakarta dan Surabaya pada tahun 2024."
)

results_id2 = ner_pipeline_id(teks_id2)

print("=== NER Teks Ulasan Keuangan ===")
print(f"Teks: {teks_id2}\n")
print(f"{'Token':<30} {'Entitas':<10} {'Score'}")
print('-' * 55)
for r in results_id2:
    print(f"{r['word']:<30} {r['entity_group']:<10} {r['score']:.4f}")

=== NER Teks BPJS ===
Teks: BPJS Kesehatan bekerja sama dengan Kementerian Kesehatan untuk meningkatkan kualitas layanan JKN di Jakarta dan Surabaya pada tahun 2023.

Token                          Entitas    Score
-------------------------------------------------------
bpjs kesehatan                 NOR        0.8068
kementerian kesehatan          NOR        0.9829
##n                            PRD        0.4112
jakarta                        GPE        0.9974
surabaya                       GPE        0.9815
2023                           DAT        0.9162

## 7) Terapkan NER ke Seluruh Dataset Honest Review

Load dataset `cleandata.csv` dan terapkan model NER bahasa Indonesia ke kolom `text_final`. Hasil entitas disimpan sebagai kolom baru `NER_Results` dalam format string.

In [15]:
import pandas as pd
import unicodedata
import re

# Load dataset Honest Review
file_path = '../Week 3/cleandata.csv'
df_text = pd.read_csv(file_path)
print(f"Jumlah data: {len(df_text)}")
print(f"Kolom: {list(df_text.columns)}")
df_text['text_final'].head()

Jumlah data: 39164
Kolom: ['score', 'content', 'text_final', 'reviewCreatedVersion']

0    kali kartu kredit cocok anak muda update alam ...
1    hasil layan cs nama sangat sopan jelas sangat ...
2                                           cepat aman
3                                              cs baik
4                                           jelas baik
Name: text_final, dtype: str

In [16]:
def clean_text(text):
    """Bersihkan teks dari karakter non-printable dan non-ASCII."""
    text = str(text)
    text = ''.join(char for char in text if unicodedata.category(char)[0] != 'C')
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    return text


def perform_ner(text, max_length=512):
    """
    Terapkan NER pada satu teks.
    Potong teks jika melebihi max_length karakter untuk efisiensi.
    Return string entitas yang ditemukan (deduplikasi).
    """
    cleaned = clean_text(text)[:max_length]
    results = ner_pipeline_id(cleaned, aggregation_strategy="simple")
    entities = list(set(f"{r['word']} ({r['entity_group']})" for r in results))
    return ', '.join(entities) if entities else '-'


def safe_perform_ner(text):
    """Wrapper dengan penanganan error."""
    try:
        return perform_ner(text)
    except Exception as e:
        return f"Error: {str(e)[:50]}"


print("Fungsi NER siap digunakan.")

Fungsi NER siap digunakan.

In [17]:
# Terapkan NER ke seluruh dataset
# Catatan: Proses ini mungkin memakan beberapa menit tergantung ukuran dataset
print("Memproses NER untuk seluruh dataset...")
df_text['NER_Results'] = df_text['text_final'].apply(safe_perform_ner)
print("NER selesai!")

# Tampilkan contoh hasil
print("\nContoh hasil NER:")
df_text[['text_final', 'NER_Results']].head(5)

Memproses NER untuk seluruh dataset...
NER selesai!

Contoh hasil NER:

                                          text_final    NER_Results
0  kali kartu kredit cocok anak muda update alam ...              -
1  hasil layan cs nama sangat sopan jelas sangat ...  ##an cs (ORG)
2                                         cepat aman              -
3                                            cs baik              -
4                                         jelas baik              -

## 8) Simpan Hasil NER

Simpan DataFrame dengan hasil NER ke file CSV agar bisa digunakan untuk analisis lanjutan.

In [18]:
output_file = 'Honest_Reviews_NER.csv'
df_text.to_csv(output_file, index=False)
print(f"Hasil NER disimpan ke '{output_file}'")
print(f"Total ulasan diproses: {len(df_text):,}")

# Tampilkan semua data
df_text

Hasil NER disimpan ke 'Honest_Reviews_NER.csv'
Total ulasan diproses: 39,164

,score,content,text_final,reviewCreatedVersion,NER_Results
0,5,ini adalah pertama kali saya menggunakan kartu...,kali kartu kredit cocok anak muda update alam ...,3.831.0,-
1,5,"pengajuan berhasil, pelayanan utk CS atas nama...",hasil layan cs nama sangat sopan jelas sangat ...,3.833.1,##an cs (ORG)
2,5,Pengajuan cepat dan aman..,cepat aman,3.833.1,-
3,5,cs Ridwan terbaik,cs baik,3.833.1,-
4,5,penjelasan yang baik oleh mba rima,jelas baik,3.833.1,-
...,...,...,...,...,...
39159,5,Keren banget aplikasinya! Semua proses pengaju...,keren banget proses cepat tidak ribet tidak tu...,2.650.3,"the (EVT), next (PRD)"
39160,5,Beru kali ini nemu proses kartu kredit secepat...,kali nemu proses kartu kredit cepat menit lang...,NaN,-
39161,5,"Suka banget sama aplikasi ini, mudah mengajuka...",suka banget mudah via tidak ribet fleksible gu...,2.624.2,-
39162,5,Akhirnya ada juga aplikasi kartu kredit di Ind...,kartu kredit indonesia proses cepat mudah simp...,NaN,"kartu (ORG), kredit indonesia (PRD)"
39163,5,Proses pengajuannya cepat dan langsung bisa di...,proses cepat langsung tunggu kartu fisik,2.624.2,kartu fisik (PRD)